[package]
name = "storm-cli"
description = "Storm node command-line interface"
version = "0.8.0-alpha.1"
authors = ["Dr. Maxim Orlovsky <orlovsky@lnp-bp.org>"]
license = "MIT"
keywords = ["daemon", "microservice", "lightning-network", "lnp-bp", "storage"]
categories = ["network-programming", "command-line-utilities"]
edition = "2021"
rust-version = "1.56.0"
readme = "../README.md"

[[bin]]
path = "src/main.rs"
name = "storm-cli"

[dependencies]
amplify = "3.12.0"
internet2 = "0.8.0-beta.1"
microservices = { version = "0.8.0-rc.4", default-features = false, features = ["cli"] }
storm_rpc = { version = "0.8.0-alpha.1", path = "../rpc" }
clap = { version = "~3.1.18", features = ["derive", "env"] }
log = "0.4.14"
colored = "2"